apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: g4
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:stable-alpine
        ports:
        - containerPort: 80