apiVersion: v1
kind: Service
metadata:
  name: group4-lb
  namespace: g4
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: group4-lb-backend
  namespace: g4
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer