apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: g4
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: nginx:stable-alpine
        ports:
        - containerPort: 80